# Generated by Django 2.2.4 on 2019-10-30 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(default='Tell People About Yourself', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(18)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='F', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_tongue',
            field=models.CharField(choices=[('H', 'Hindi'), ('E', 'English'), ('J', 'Japanese'), ('O', 'Others')], default='E', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(choices=[('H', 'Hindu'), ('C', 'Christian'), ('M', 'Muslim'), ('O', 'Others'), ('N', 'None')], default='N', max_length=1),
            preserve_default=False,
        ),
    ]
